version: "3.9"
services:
  kittychan:
    build: .
    image: kittychan-api
    container_name: kittychan-api
    ports:
      - "5000:3000"
    networks:
    - kittychan-network

networks:
  kittychan-network:
    name: kittychan-network